const NODE_SIZE: number = 90;
// const NODE_SIZE: number = 120;
const DEATH_THRESHOLD: number = 0.02;
const SIMULATION_LENGTH: number = 20;

const DATABASE_VERSION = 4;
const DATABASE_LOCKED = true;

const UNIVERSEUM = true;

const IDLE_TIME = 5;
const IDLE_FADE = 5;
const QUESTION_TIME = 12;

export {
	NODE_SIZE,
	DEATH_THRESHOLD,
	SIMULATION_LENGTH,
	DATABASE_VERSION,
	DATABASE_LOCKED,
	UNIVERSEUM,
	IDLE_TIME,
	IDLE_FADE,
	QUESTION_TIME,
};